import type { ProfessionalScenarioDefinition } from "./types";

export const industrialDataAnomalyScenario: ProfessionalScenarioDefinition = {
  id: "INDUSTRIAL_DATA_ANOMALY_REPORT",
  slug: "industrial-data-anomaly-report",
  version: 1,
  title: "Anomalie de données industrielles",
  domain: "Industrie 4.0 · qualité des données",
  role: "Contributeur junior Industrie 4.0 orienté données",
  context: "Tu participes à la vérification d’un indicateur énergétique avant un point de pilotage.",
  objectives: ["Repérer une anomalie dans un échantillon synthétique.", "Séparer ce qui est observé de ce qui reste à vérifier.", "Proposer une action concrète et rédiger un point de situation."],
  estimatedMinutes: 20,
  competencies: ["DATA_ANOMALY_IDENTIFICATION", "FACT_VS_ASSUMPTION", "PROFESSIONAL_STATUS_UPDATE", "ACTIONABLE_NEXT_STEP"],
  dataClassification: "TRAINING_SYNTHETIC",
  scenarioBrief: "Un KPI énergie par tonne semble inhabituel sur un lot. Ton responsable attend une analyse prudente et une prochaine action, pas une conclusion prématurée.",
  artifacts: [{
    id: "synthetic-batch-sample",
    title: "Extrait de lots de production",
    description: "Échantillon fictif préparé uniquement pour l’apprentissage.",
    dataClassification: "TRAINING_SYNTHETIC",
    columns: ["Batch_ID", "Site", "Produced_Tons", "Energy_kWh", "Energy_kWh_per_Ton"],
    rows: [
      { Batch_ID: "B-101", Site: "Site Nord", Produced_Tons: 100, Energy_kWh: 5100, Energy_kWh_per_Ton: 51 },
      { Batch_ID: "B-102", Site: "Site Nord", Produced_Tons: 96, Energy_kWh: 4992, Energy_kWh_per_Ton: 52 },
      { Batch_ID: "B-103", Site: "Site Nord", Produced_Tons: 104, Energy_kWh: 5304, Energy_kWh_per_Ton: 51 },
      { Batch_ID: "B-104", Site: "Site Nord", Produced_Tons: 98, Energy_kWh: 14700, Energy_kWh_per_Ton: 150 },
      { Batch_ID: "B-105", Site: "Site Nord", Produced_Tons: 102, Energy_kWh: 5304, Energy_kWh_per_Ton: 52 },
    ],
  }],
  tasks: [
    {
      id: "identify-anomaly", type: "INSPECT", phase: "ANALYSIS", title: "Ce que tu observes",
      instruction: "Quel lot mérite une vérification prioritaire au regard de l’énergie par tonne ?", responseType: "MULTIPLE_CHOICE",
      choices: [{ id: "B-101", label: "B-101 · 51 kWh/t" }, { id: "B-103", label: "B-103 · 51 kWh/t" }, { id: "B-104", label: "B-104 · 150 kWh/t" }, { id: "B-105", label: "B-105 · 52 kWh/t" }],
      correctChoiceId: "B-104",
      hintLevels: ["Compare la même métrique sur tous les lots.", "Observe l’énergie relativement au tonnage produit.", "Un lot affiche environ trois fois la valeur de ses voisins."],
      errorTags: ["MISSED_DATA_ANOMALY"],
      successFeedback: "Observation correcte : B-104 se distingue nettement dans cet échantillon.",
      retryFeedback: "Compare Energy_kWh_per_Ton entre les lots, sans conclure encore sur la cause.",
      evaluationDimensions: ["FACTUAL_ACCURACY", "PROBLEM_IDENTIFICATION"],
    },
    {
      id: "separate-fact-assumption", type: "ANALYZE", phase: "ANALYSIS", title: "Fait ou hypothèse",
      instruction: "Quelle formulation peut être affirmée avec certitude à partir du seul tableau ?", responseType: "MULTIPLE_CHOICE",
      choices: [
        { id: "fact", label: "B-104 affiche 150 kWh/t, contre 51–52 kWh/t pour les autres lots présentés." },
        { id: "failure", label: "La machine utilisée pour B-104 est en panne." },
        { id: "inefficient", label: "Le procédé du site est forcément inefficace." },
      ],
      correctChoiceId: "fact",
      hintLevels: ["Reste limité à ce qui est visible.", "Une cause n’est pas démontrée par cet extrait.", "Choisis la formulation qui compare uniquement les valeurs affichées."],
      errorTags: ["CONFUSED_FACT_AND_ASSUMPTION", "OVERCLAIM_WITHOUT_EVIDENCE"],
      successFeedback: "Exact : la comparaison est un fait observé; la cause reste inconnue.",
      retryFeedback: "Cette formulation dépasse les éléments disponibles. Distingue observation et cause supposée.",
      evaluationDimensions: ["FACTUAL_ACCURACY", "UNCERTAINTY_HANDLING"],
    },
    {
      id: "choose-next-action", type: "DECIDE", phase: "DECISION", title: "Décision",
      instruction: "Quelle est la prochaine action la plus professionnelle avant d’alerter sur une défaillance opérationnelle ?", responseType: "MULTIPLE_CHOICE",
      choices: [
        { id: "verify-source", label: "Vérifier la source, l’unité et le calcul de B-104, puis comparer avec les données voisines." },
        { id: "stop-site", label: "Demander immédiatement l’arrêt du site." },
        { id: "ignore", label: "Ignorer l’écart car il ne concerne qu’un lot." },
      ],
      correctChoiceId: "verify-source",
      hintLevels: ["Cherche une action proportionnée à l’incertitude.", "Commence par confirmer la qualité de la donnée.", "Vérifie source, unité et calcul avant une conclusion opérationnelle."],
      errorTags: ["NO_NEXT_ACTION", "OVERCLAIM_WITHOUT_EVIDENCE"],
      successFeedback: "Décision proportionnée : vérifier la donnée avant d’attribuer une cause.",
      retryFeedback: "L’action proposée doit réduire l’incertitude sans sur-réagir.",
      evaluationDimensions: ["UNCERTAINTY_HANDLING", "ACTIONABILITY"],
    },
    {
      id: "professional-update", type: "WRITE", phase: "PROFESSIONAL_RESPONSE", title: "Compte rendu",
      instruction: "Écris un point de situation à ton responsable en 5 à 8 lignes : observation, importance, incertitude et prochaine action.", responseType: "LONG_TEXT",
      expectedConceptGroups: [["B-104", "lot 104"], ["150", "énergie par tonne", "kWh/t"], ["à vérifier", "possible", "peut", "incertitude", "ne permet pas de conclure"], ["vérifier", "contrôler", "source", "unité", "calcul"]],
      minLength: 120,
      hintLevels: ["Commence par une phrase qui décrit uniquement ce que tu observes.", "Ajoute ensuite ce que tu ne peux pas encore confirmer.", "Termine par une action concrète : vérifier la source, comparer les lots, ou demander une validation."],
      errorTags: ["OVERCLAIM_WITHOUT_EVIDENCE", "NO_NEXT_ACTION"],
      successFeedback: "Le point de situation est factuel, prudent et orienté vers l’action.",
      retryFeedback: "Renforce la structure : observation précise, incertitude explicite et prochaine vérification.",
      evaluationDimensions: ["FACTUAL_ACCURACY", "UNCERTAINTY_HANDLING", "ACTIONABILITY", "COMMUNICATION_CLARITY"],
    },
    {
      id: "self-check", type: "VERIFY", phase: "SELF_CHECK", title: "Auto-contrôle professionnel",
      instruction: "Quelle vérification finale évite de transformer une hypothèse en fait ?", responseType: "MULTIPLE_CHOICE",
      choices: [
        { id: "labels", label: "Relire chaque affirmation et marquer ce qui est observé, supposé ou encore à vérifier." },
        { id: "jargon", label: "Ajouter davantage de jargon technique." },
        { id: "certainty", label: "Supprimer les marques d’incertitude pour paraître plus sûr." },
      ],
      correctChoiceId: "labels",
      hintLevels: ["Contrôle la nature de chaque affirmation.", "La clarté compte plus que le jargon.", "Vérifie les frontières entre fait, hypothèse et action."],
      errorTags: ["CONFUSED_FACT_AND_ASSUMPTION"],
      successFeedback: "Bon réflexe : qualifier chaque affirmation protège la qualité de la décision.",
      retryFeedback: "Le contrôle attendu porte sur le niveau de certitude des affirmations.",
      evaluationDimensions: ["UNCERTAINTY_HANDLING", "COMMUNICATION_CLARITY"],
    },
  ],
  decisionPoints: [{ id: "source-verification", prompt: "Faut-il conclure à un incident opérationnel ?", expectedAction: "Vérifier d’abord la donnée et conserver explicitement l’incertitude." }],
  communicationTask: {
    taskId: "professional-update",
    expectedStructure: ["observation", "importance", "incertitude", "prochaine action"],
    optionalEnglishPrompt: "Explain the observed anomaly and the next verification step to an international colleague.",
  },
  completionCriteria: { requiredTaskIds: ["identify-anomaly", "separate-fact-assumption", "choose-next-action", "professional-update", "self-check"], maxStateFromGuidedScenario: "PRACTICED" },
  evidencePolicy: { sourceClassification: "PERSONAL", retainAttemptHistory: true, retainedRequiresDelayedRetrieval: true },
  evaluationPolicy: {
    dimensions: ["FACTUAL_ACCURACY", "PROBLEM_IDENTIFICATION", "UNCERTAINTY_HANDLING", "ACTIONABILITY", "COMMUNICATION_CLARITY"],
    aggregatePercentageForbidden: true,
  },
};
