import type { DeepMasteryDefinition } from "./types";

export const csvDelimiterMastery: DeepMasteryDefinition = {
  id: "deep-mastery-csv-delimiter",
  slug: "deep-mastery-csv-delimiter",
  version: 1,
  title: "Maîtriser le diagnostic d’un CSV",
  subject: "Excel · Import CSV",
  competencies: ["EXCEL_CSV_IMPORT"],
  estimatedMinutes: 25,
  foundation: {
    id: "foundation",
    phase: "FOUNDATION",
    title: "Le rôle du délimiteur",
    instruction: "Lis ce repère, puis reformule-le mentalement avant de continuer.",
    why: "Un bon diagnostic commence par distinguer la structure du fichier de son affichage dans Excel.",
    keyPoints: [
      "Un CSV contient des champs séparés par un caractère: virgule, point-virgule ou tabulation.",
      "Excel doit utiliser le même séparateur pour répartir les champs en colonnes.",
      "Si tout apparaît dans une seule colonne, inspecte d’abord le fichier brut et l’aperçu d’import.",
    ],
  },
  mentalModel: {
    id: "mental-model",
    phase: "MENTAL_MODEL",
    title: "Séparer structure et encodage",
    instruction: "Construis ce modèle mental: le délimiteur sépare les champs; l’encodage représente les caractères.",
    keyPoints: [
      "Délimiteur incorrect: nombre de colonnes incorrect.",
      "Encodage incorrect: caractères comme é, à ou ç deviennent illisibles.",
      "Les deux réglages peuvent être vérifiés dans l’aperçu, mais ils ne corrigent pas le même problème.",
    ],
  },
  questions: [
    {
      id: "retrieval-delimiter",
      phase: "RETRIEVAL",
      type: "MULTIPLE_CHOICE",
      title: "Récupère l’idée essentielle",
      instruction: "Un CSV s’ouvre dans une seule colonne. Quel réglage vérifies-tu en premier ?",
      difficulty: 1,
      conceptId: "CSV_DELIMITER_DIAGNOSIS",
      responseModes: ["WRITE"],
      choices: [
        { id: "delimiter", label: "Le délimiteur utilisé pendant l’import" },
        { id: "encoding", label: "L’encodage des caractères" },
        { id: "alignment", label: "L’alignement des cellules" },
      ],
      correctChoiceId: "delimiter",
      misconceptionTags: ["CSV_DELIMITER_DIAGNOSIS"],
      hintLevels: ["Observe ce qui sépare les valeurs dans le fichier brut.", "Compare ce caractère au séparateur choisi dans l’aperçu.", "Cherche le réglage qui transforme une ligne en plusieurs colonnes."],
      successFeedback: "Exact. Une seule colonne indique d’abord un délimiteur mal interprété.",
      retryFeedback: "Ce réglage ne détermine pas la séparation des champs. Reprends le symptôme observé.",
    },
    {
      id: "challenge-preview",
      phase: "CHALLENGE",
      type: "SHORT_TEXT",
      title: "Applique le diagnostic",
      instruction: "L’aperçu montre Product,Site,Energy dans une seule colonne. Explique l’action à faire dans Excel.",
      why: "Tu passes de la reconnaissance à une action justifiée.",
      difficulty: 3,
      conceptId: "CSV_DELIMITER_DIAGNOSIS",
      responseModes: ["WRITE"],
      expectedConceptGroups: [["délimiteur", "delimiteur", "séparateur", "separateur"], ["virgule", "comma"]],
      minLength: 24,
      misconceptionTags: ["CSV_DELIMITER_DIAGNOSIS"],
      hintLevels: ["Nomme le réglage à modifier.", "Repère le caractère visible entre Product, Site et Energy.", "Indique que le séparateur d’import doit être la virgule, puis vérifie l’aperçu."],
      successFeedback: "Bon diagnostic: tu relies le caractère visible au séparateur d’import.",
      retryFeedback: "Ta réponse doit nommer le réglage et le caractère attendu dans cet exemple.",
    },
  ],
  confusions: [{
    id: "confusion-encoding",
    phase: "CONFUSIONS",
    type: "MULTIPLE_CHOICE",
    title: "Distingue deux réglages",
    instruction: "Affirmation: « Le délimiteur et l’encodage sont deux noms pour le même réglage. »",
    difficulty: 4,
    conceptId: "CSV_DELIMITER_VS_ENCODING",
    responseModes: ["WRITE"],
    choices: [{ id: "true", label: "Vrai" }, { id: "false", label: "Faux" }],
    correctChoiceId: "false",
    misconceptionTags: ["CSV_DELIMITER_VS_ENCODING"],
    hintLevels: ["Demande-toi si les deux réglages changent la même chose.", "L’un agit sur les colonnes, l’autre sur les caractères.", "Une mauvaise séparation et des accents illisibles sont deux symptômes différents."],
    successFeedback: "Exact. Le délimiteur structure les champs; l’encodage représente les caractères.",
    retryFeedback: "Compare les symptômes: colonnes incorrectes versus caractères illisibles.",
  }],
  feynmanPrompt: {
    id: "feynman-explanation",
    phase: "FEYNMAN",
    type: "EXPLANATION",
    title: "Explique avec tes propres mots",
    instruction: "Explique à un étudiant pourquoi un CSV peut apparaître dans une seule colonne et comment le corriger.",
    difficulty: 2,
    conceptId: "CSV_DELIMITER_DIAGNOSIS",
    responseModes: ["WRITE", "SPEAK"],
    expectedConceptGroups: [["délimiteur", "delimiteur", "séparateur", "separateur"], ["colonne", "champs"], ["import", "aperçu", "apercu", "excel"]],
    minLength: 70,
    misconceptionTags: ["CSV_DELIMITER_DIAGNOSIS"],
    hintLevels: ["Commence par le symptôme.", "Relie le caractère du fichier au réglage d’import.", "Structure: cause, vérification dans l’aperçu, correction, résultat attendu."],
    successFeedback: "Ton explication couvre le symptôme, la cause et l’action de correction.",
    retryFeedback: "Ajoute le lien entre séparateur, aperçu d’import et répartition en colonnes.",
  },
  transferChallenge: {
    id: "held-out-semicolon",
    phase: "TRANSFER",
    type: "SHORT_TEXT",
    title: "Résous un cas nouveau",
    instruction: "Un fichier affiche: Name;Site;Energy puis A;Paris;120. Que vérifies-tu d’abord, et pourquoi ?",
    why: "Le séparateur change, mais le concept reste le même.",
    difficulty: 5,
    conceptId: "CSV_SEPARATOR_TRANSFER",
    responseModes: ["WRITE"],
    expectedConceptGroups: [["délimiteur", "delimiteur", "séparateur", "separateur"], ["point virgule", ";", "semicolon"], ["colonne", "champs", "séparer", "separer"]],
    minLength: 35,
    misconceptionTags: ["CSV_SEPARATOR_TRANSFER"],
    hintLevels: ["Observe le caractère répété entre les valeurs.", "Ce fichier n’utilise pas la virgule du cas guidé.", "Vérifie que le délimiteur d’import est le point-virgule afin de séparer les champs."],
    successFeedback: "Transfert réussi: tu as reconnu le point-virgule comme délimiteur du nouveau fichier.",
    retryFeedback: "Identifie le caractère entre Name, Site et Energy, puis explique son effet sur les colonnes.",
  },
  completionCriteria: {
    requireFeynmanSuccess: true,
    requireTransferSuccess: true,
    maxTransferHintsForDemonstrated: 1,
    maxTransferRetriesForDemonstrated: 0,
  },
  evidencePolicy: { classification: "PERSONAL", maxStateFromSingleSession: "DEMONSTRATED", retainedRequiresLaterReview: true },
};
