import type { MissionDefinition } from "./types";

export const runtimeDemoMission: MissionDefinition = {
  id: "runtime-demo-v1",
  slug: "runtime-demo",
  version: 1,
  title: "Décision fiable en 4 étapes",
  level: "Mission découverte",
  objective: "Appliquer un petit contrôle qualité avant de prendre une décision.",
  reason: "Cette mission te montre comment fonctionne ton nouvel espace d’apprentissage.",
  estimatedMinutes: 6,
  steps: [
    {
      id: "choose-first-check",
      kind: "multiple_choice",
      title: "Choisis le premier contrôle",
      instruction: "Deux fichiers affichent la même énergie, mais leurs unités ne sont pas indiquées. Que fais-tu d’abord ?",
      why: "Une valeur n’est comparable que si son unité et son contexte sont connus.",
      hints: ["Cherche ce qui permet de comparer les deux valeurs.", "Vérifie l’information qui donne un sens au nombre.", "Commence par confirmer les unités des deux fichiers."],
      choices: [
        { id: "average", label: "Calculer immédiatement une moyenne" },
        { id: "units", label: "Vérifier les unités des deux fichiers" },
        { id: "ignore", label: "Ignorer la différence" },
      ],
      correctChoiceId: "units",
      successFeedback: "Exact. Confirmer les unités évite une comparaison trompeuse.",
      retryFeedback: "Pas encore. Avant tout calcul, cherche ce qui rend les valeurs comparables.",
    },
    {
      id: "explain-check",
      kind: "short_answer",
      title: "Explique ton contrôle",
      instruction: "En une phrase, explique ce que tu dois vérifier avant de comparer les valeurs.",
      why: "Formuler le contrôle permet de vérifier que la règle est comprise, pas seulement reconnue.",
      example: "Je vérifie ... avant de ...",
      hints: ["Mentionne l’information associée à chaque valeur.", "Ta réponse doit parler des unités.", "Explique que les unités doivent être cohérentes avant la comparaison."],
      acceptedKeywords: ["unit"],
      minLength: 18,
      successFeedback: "Bien formulé. Tu relies le contrôle des unités à la comparaison.",
      retryFeedback: "Précise ce que tu vérifies avant de comparer les deux nombres.",
    },
    {
      id: "evidence-note",
      kind: "evidence_prompt",
      title: "Laisse une trace utile",
      instruction: "Rédige une courte note indiquant le problème observé et l’action à mener.",
      why: "Une trace claire aide la prochaine personne à agir sans refaire toute l’analyse.",
      example: "Problème : ... Action : ...",
      hints: ["Sépare le problème de l’action.", "Indique les unités comme point à confirmer."],
      minLength: 35,
      successFeedback: "Ta note contient assez d’information pour déclencher une action.",
      retryFeedback: "Ajoute le problème observé et une action concrète.",
    },
    {
      id: "self-check",
      kind: "self_assessment",
      title: "Évalue ton ressenti",
      instruction: "Comment te sens-tu après cette mission ?",
      successFeedback: "Merci. Ton ressenti est enregistré séparément de ta performance.",
      retryFeedback: "Choisis un niveau de confiance pour terminer.",
    },
  ],
};

