import type { MissionDefinition } from "./types";

export const excelLevel1Mission: MissionDefinition = {
  id: "excel-csv-foundations-level-1-v1",
  slug: "excel-csv-foundations-level-1",
  version: 1,
  title: "Excel CSV Foundations",
  subject: "Analyse de données",
  competency: "EXCEL_CSV_IMPORT",
  level: "Niveau 1 — Import CSV",
  objective: "Importer un CSV dans Excel et vérifier que les données sont correctement séparées en colonnes.",
  reason: "Cette mission cible ton principal blocage observé pendant la baseline : importer correctement un fichier CSV dans Excel.",
  estimatedMinutes: 20,
  completionStatus: "PRACTICED",
  completionSummary: [
    "CSV ouvert et importé",
    "Colonnes et délimiteur vérifiés",
    "Valeur Energy_kWh manquante identifiée",
    "Preuve locale enregistrée",
  ],
  steps: [
    {
      id: "understand-objective",
      kind: "information",
      title: "Comprends l’objectif",
      instruction: "Tu vas importer un CSV dans Excel, puis vérifier que ses cinq champs apparaissent dans cinq colonnes distinctes.",
      why: "Un import incorrect rend les contrôles et calculs suivants peu fiables.",
      successFeedback: "Objectif compris. Tu peux maintenant récupérer le fichier d’entraînement.",
      retryFeedback: "Confirme l’objectif pour continuer.",
    },
    {
      id: "access-training-csv",
      kind: "resource",
      title: "Récupère le CSV d’entraînement",
      instruction: "Télécharge le fichier synthétique Level 1 et conserve le CSV brut inchangé.",
      resource: {
        href: "/training-data/excel-csv-foundations/level-1-import.csv",
        label: "Télécharger level-1-import.csv",
        downloadName: "level-1-import.csv",
        classification: "TRAINING_SYNTHETIC",
      },
      successFeedback: "Fichier identifié. Ouvre maintenant Excel avec un classeur vide.",
      retryFeedback: "Télécharge ou localise le fichier avant de continuer.",
    },
    {
      id: "import-in-excel",
      kind: "information",
      title: "Importe le fichier dans Excel",
      instruction: "Dans Excel, ouvre Données → Depuis Texte/CSV, puis sélectionne level-1-import.csv.",
      details: [
        "Dans l’aperçu, choisis UTF-8 si Excel demande l’encodage.",
        "Choisis Virgule (Comma) comme délimiteur.",
        "Vérifie l’aperçu avant de charger les données.",
      ],
      why: "L’aperçu permet de corriger le délimiteur avant que les données soient chargées.",
      successFeedback: "Import réalisé. Contrôle maintenant le résultat visible dans la feuille.",
      retryFeedback: "Effectue l’import dans Excel avant de continuer.",
    },
    {
      id: "check-columns",
      kind: "multiple_choice",
      title: "Vérifie les colonnes",
      instruction: "Après l’import, quelle observation confirme que le délimiteur est correct ?",
      why: "Le fichier source contient cinq champs séparés par des virgules.",
      hints: [
        "Regarde comment Excel sépare les valeurs.",
        "Vérifie le délimiteur détecté pendant l’import.",
        "Le fichier utilise des virgules : choisis Virgule dans l’aperçu d’import.",
      ],
      choices: [
        { id: "separate-columns", label: "Les données sont séparées en cinq colonnes." },
        { id: "single-column", label: "Toutes les données apparaissent dans une seule colonne." },
        { id: "incorrect-columns", label: "Les colonnes semblent décalées ou incorrectes." },
        { id: "unsure", label: "Je ne suis pas sûr." },
      ],
      correctChoiceId: "separate-columns",
      successFeedback: "Exact. Cinq colonnes distinctes confirment que la virgule a été interprétée correctement.",
      retryFeedback: "Ce résultat n’est pas encore correct. Reviens à l’aperçu et vérifie le délimiteur.",
    },
    {
      id: "find-anomaly",
      kind: "short_answer",
      title: "Repère l’anomalie",
      instruction: "Quelle anomalie vois-tu dans les huit lignes ? Réponds avec la colonne concernée et, si possible, le lot.",
      why: "Une cellule vide peut empêcher un calcul ou réduire la fiabilité d’une décision.",
      hints: [
        "Compare les lignes colonne par colonne.",
        "Regarde particulièrement les valeurs d’énergie.",
        "Une cellule Energy_kWh est vide.",
      ],
      acceptedKeywordGroups: [
        ["energy_kwh", "energy kwh", "énergie", "energie"],
        ["vide", "manquante", "manquant", "absente", "absent"],
      ],
      minLength: 12,
      successFeedback: "Bien vu. La valeur Energy_kWh du lot L1-005 est vide et doit être signalée, sans être inventée.",
      retryFeedback: "Ta réponse ne permet pas encore d’identifier précisément la valeur manquante.",
    },
    {
      id: "submit-evidence",
      kind: "evidence_submission",
      title: "Ajoute une preuve locale",
      instruction: "Ajoute une capture de la feuille montrant les cinq colonnes, ou ton fichier XLSX importé.",
      why: "La preuve confirme que tu as réellement effectué l’import dans Excel.",
      successFeedback: "Preuve enregistrée uniquement sur cet appareil.",
      retryFeedback: "Ajoute une image ou un fichier XLSX valide pour continuer.",
    },
    {
      id: "self-evaluation",
      kind: "self_assessment",
      title: "Évalue ton autonomie",
      instruction: "De 1 à 5, à quel point pourrais-tu refaire seul cet import avec le bon délimiteur ?",
      why: "Ta confiance est enregistrée séparément de ta performance.",
      successFeedback: "Auto-évaluation enregistrée. Elle ne change pas le résultat de l’exercice.",
      retryFeedback: "Choisis un niveau entre 1 et 5.",
    },
    {
      id: "confirm-completion",
      kind: "information",
      title: "Confirme ce que tu as démontré",
      instruction: "Tu as importé le CSV, vérifié les colonnes, identifié la valeur manquante et fourni une preuve locale.",
      why: "Cette première réussite indique une compétence pratiquée, pas encore retenue à long terme.",
      successFeedback: "Mission prête à être terminée.",
      retryFeedback: "Confirme le récapitulatif pour terminer.",
    },
  ],
};
